apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-app-health-validator
data:
  #update queries 
  datadog-app-health-validator: |
    {
      "filterKey": "${app_key},${host_key}",
      "data": {
        "percent_diff_threshold": "hard",
        "isNormalize": false,
        "groups": [
          {
            "metrics": [
              {
                "metricType": "ADVANCED",
                "metricWeight": 1,
                "nanStrategy": "ReplaceWithZero",
                "accountName": "datadog-argo-isd-saas",
                "riskDirection": "HigherOrLower",
                "customThresholdHigher": 50,
                "name": "SELECT average(duration)*1000 FROM Transaction WHERE appName = '${app_key}' AND host RLIKE '${host_key}'",
                "criticality": "Normal",
                "customThresholdLower": 50,
                "watchlist": false
              }
            ],
            "group": "Transaction Time"
          },
          {
            "metrics": [
              {
                "metricType": "ADVANCED",
                "metricWeight": 1,
                "nanStrategy": "ReplaceWithZero",
                "accountName": "datadog-argo-isd-saas",
                "riskDirection": "HigherOrLower",
                "customThresholdHigher": 50,
                "name": "SELECT percentile(duration, 95) * 1000 FROM Transaction WHERE appName='${app_key}' AND host RLIKE '${host_key}'",
                "criticality": "Normal",
                "customThresholdLower": 50,
                "watchlist": false
              }
            ],
            "group": "95th Percentile"
          },
          {
            "metrics": [
              {
                "metricType": "ADVANCED",
                "metricWeight": 1,
                "nanStrategy": "ReplaceWithZero",
                "accountName": "datadog-argo-isd-saas",
                "riskDirection": "HigherOrLower",
                "customThresholdHigher": 50,
                "name": "SELECT percentile(duration, 99) * 1000 FROM Transaction WHERE appName='${app_key}' AND host RLIKE '${host_key}'",
                "criticality": "Normal",
                "customThresholdLower": 50,
                "watchlist": false
              }
            ],
            "group": "99th Percentile"
          },
          {
            "metrics": [
              {
                "metricType": "ADVANCED",
                "metricWeight": 1,
                "nanStrategy": "ReplaceWithZero",
                "accountName": "datadog-argo-isd-saas",
                "riskDirection": "HigherOrLower",
                "customThresholdHigher": 50,
                "name": "SELECT percentile(duration, 90) * 1000 FROM Transaction WHERE appName='${app_key}' AND host RLIKE '${host_key}'",
                "criticality": "Normal",
                "customThresholdLower": 50,
                "watchlist": false
              }
            ],
            "group": "90th Percentile"
          },
          {
            "metrics": [
              {
                "metricType": "ADVANCED",
                "metricWeight": 1,
                "nanStrategy": "ReplaceWithZero",
                "accountName": "datadog-argo-isd-saas",
                "riskDirection": "HigherOrLower",
                "customThresholdHigher": 50,
                "name": "SELECT count(apm.service.error.count) / count(apm.service.transaction.duration) FROM Metric WHERE appName = '${app_key}' AND host RLIKE '${host_key}'",
                "criticality": "Normal",
                "customThresholdLower": 50,
                "watchlist": false
              }
            ],
            "group": "Error Rate"
          },
          {
            "metrics": [
              {
                "metricType": "ADVANCED",
                "metricWeight": 1,
                "nanStrategy": "ReplaceWithZero",
                "accountName": "datadog-argo-isd-saas",
                "riskDirection": "HigherOrLower",
                "customThresholdHigher": 50,
                "name": "SELECT apdex(apm.service.apdex) FROM Metric WHERE appName='${app_key}' AND host RLIKE '${host_key}'",
                "criticality": "Normal",
                "customThresholdLower": 50,
                "watchlist": false
              }
            ],
            "group": "Apdex"
          },
          {
            "metrics": [
              {
                "metricType": "ADVANCED",
                "metricWeight": 1,
                "nanStrategy": "ReplaceWithZero",
                "accountName": "datadog-argo-isd-saas",
                "riskDirection": "HigherOrLower",
                "customThresholdHigher": 50,
                "name": "SELECT average(newrelic.timeslice.value) * 1000 FROM Metric WHERE metricTimesliceName = 'CPU/User/Utilization' AND appName = '${app_key}' AND host RLIKE '${host_key}'",
                "criticality": "Normal",
                "customThresholdLower": 50,
                "watchlist": false
              }
            ],
            "group": "CPU Utilization"
          },
          {
            "metrics": [
              {
                "metricType": "ADVANCED",
                "metricWeight": 1,
                "nanStrategy": "ReplaceWithZero",
                "accountName": "datadog-argo-isd-saas",
                "riskDirection": "HigherOrLower",
                "customThresholdHigher": 50,
                "name": "SELECT (average(apm.service.memory.physical) * rate(count(apm.service.instance.count), 1 minute)) / 1000 as memoryUsage FROM Metric WHERE (appName = '${app_key}' AND host RLIKE '.*${pod_key}.*')",
                "criticality": "Normal",
                "customThresholdLower": 50,
                "watchlist": false
              }
            ],
            "group": "Memory Consumption"
          }
        ]
      },
      "templateName": "datadog-app-health-validator",
      "advancedProvider": "NEWRELIC"
    }
